import Link from "next/link";
import { ArrowRight, Bell, Check, Copy, FileCheck2, Plus, Send, ShieldCheck, Sparkles } from "lucide-react";
import { ContributionStatus } from "@/components/status-pill";
import { DashboardShell } from "@/components/dashboard-shell";
import { ProgressRing } from "@/components/progress-ring";
import { contributions } from "@/lib/demo-data";

export default async function Dashboard({ searchParams }: { searchParams: Promise<{ view?: string }> }) {
  const candidate = (await searchParams).view === "candidate";
  if (candidate) return <DashboardShell candidate><div className="dashboard-head"><div><span className="eyebrow">Candidate dashboard</span><h1>Buenas, Martina.</h1><p>Tu lugar en la red comienza con personas que ya te conocen.</p></div><button className="icon-button"><Bell size={18} /></button></div><section className="candidate-progress-card"><ProgressRing value={3} total={5} /><div><span className="eyebrow">Confianza comunitaria</span><h2>Te faltan 2 vouches</h2><p>Pide validación solamente a miembros que te conocen y reconocen tu vínculo con el ecosistema.</p><div className="hero-actions"><button className="button button-primary"><Send size={15} /> Solicitar vouch</button><button className="button button-secondary"><Copy size={15} /> Copiar mi link</button></div></div><div className="candidate-steps"><span className="done"><Check size={14} /> Perfil creado</span><span className="done"><Check size={14} /> 3 personas te conocen</span><span>2 vouches pendientes</span><span>Ingreso a Chile DAO</span></div></section><section className="dash-section"><div className="dash-section-head"><div><span className="eyebrow">Tus validadores</span><h2>Personas que te conocen</h2></div></div><div className="vouch-list">{["Camila Soto", "Tomás Alarcón", "Isidora Rojas"].map((name, i) => <div key={name}><span className={`avatar avatar-small avatar-tone-${i}`}>{name.split(" ").map((x) => x[0]).join("")}</span><span><b>{name}</b><small>Vouch activo · Público</small></span><ShieldCheck size={17} /></div>)}</div></section></DashboardShell>;
  return <DashboardShell><div className="dashboard-head"><div><span className="eyebrow">Member dashboard</span><h1>Buenas, Camila.</h1><p>Tu red tiene 3 solicitudes que necesitan contexto.</p></div><Link className="button button-primary" href="/dashboard/contributions"><Plus size={16} /> Nueva contribution</Link></div><div className="metric-grid"><article><ShieldCheck /><span>Community trust</span><b>12</b><small>vouches de membresía</small></article><article><FileCheck2 /><span>Trabajo demostrado</span><b>9</b><small>contributions verificadas</small></article><article><Sparkles /><span>Reputación profesional</span><b>29</b><small>endorsements recibidos</small></article></div><section className="dash-section"><div className="dash-section-head"><div><span className="eyebrow">Requiere tu atención</span><h2>Solicitudes pendientes</h2></div><Link className="arrow-link" href="/dashboard/requests">Ver todas <ArrowRight size={15} /></Link></div><div className="request-list"><article><span className="request-type trust">Vouch</span><div><b>¿Conoces a Martina Sáez?</b><p>Te pidió confirmar su vínculo con el ecosistema.</p></div><Link href="/vouch/demo-martina">Revisar <ArrowRight size={14} /></Link></article><article><span className="request-type work">Trabajo</span><div><b>Passkey wallet prototype</b><p>Benjamín solicita validar esta contribution.</p></div><Link href="/dashboard/requests">Revisar <ArrowRight size={14} /></Link></article></div></section><section className="dash-section"><div className="dash-section-head"><div><span className="eyebrow">Tu actividad</span><h2>Contributions recientes</h2></div></div><div className="compact-work-list">{contributions.filter((c) => c.authorSlug === "camila-soto").slice(0, 3).map((item) => <Link key={item.id} href={`/projects/${item.projectSlug}`}><div><ContributionStatus status={item.status} /><b>{item.title}</b><span>{item.project}</span></div><ArrowRight size={17} /></Link>)}</div></section></DashboardShell>;
}
